use anyhow::Result;
use bnk::process::{pack_bnk, unpack_bnk};
use clap::Subcommand;
use std::path::PathBuf;

#[derive(Subcommand)]
pub enum BnkCommands {
    /// Unpack BNK file (Binary -> JSON + WEM extraction)
    Unpack {
        /// Input file
        input: PathBuf,
        /// Output file (optional)
        #[arg(short, long)]
        output: Option<PathBuf>,
        /// Disable WEM extraction
        #[arg(long)]
        no_extract: bool,
    },
    /// Pack a BNK file from JSON and WEM files
    Pack {
        /// Input JSON file (generated by unpack-bnk)
        #[arg(short = 'j', long)]
        json: PathBuf,
        /// Directory containing WEM files
        #[arg(short = 'w', long)]
        wems: PathBuf,
        /// Output BNK file
        #[arg(short, long)]
        output: PathBuf,
    },
}

pub fn handle(cmd: BnkCommands) -> Result<()> {
    match cmd {
        BnkCommands::Unpack {
            input,
            output,
            no_extract,
        } => Ok(unpack_bnk(&input, &output, no_extract)?),
        BnkCommands::Pack { json, wems, output } => Ok(pack_bnk(&json, &wems, &output)?),
    }
}
